### ISSUE TITLE
Config files not found

### ISSUE THREAD

**Issue by codesxt** [kykleung/RFS-SLAM#1]
Hi. I compiled the last version of the code and it compiled perfectly, but when I try to run rbphdslam2dSim or fastslam2dSim they can't find their respective configuration files. I've searched for them in the folders but they don't seem to be anywhere. I copied the cfg folder from the previous version but now the program seems to expect an xml file instead.

The error I'm getting when I run rbphdslam2dSim is this:

```
Configuration file: cfg/rbphdslam2dSim.xml
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::xml_parser::xml_parser_error> >'
  what():  cfg/rbphdslam2dSim.xml: cannot open file
Abortado (`core' generado)
```

I'd be very happy if you could help me try the program properly.

**Comment by kykleung** [comment]
Hi, the missing config file folder has been added. It was missed when v1.2 of the library was introduced. There are changes to the way in running the executables. Type `rbphdslam2dSim -h` for more details.

**Comment by codesxt** [comment]
It now works like a charm. Thank you!
